server:
  port: 8080
api:
  prefix: /api/v1
spring:
  application:
    name: Travel-app
  datasource:
    url: jdbc:mysql://root:sJvHdWWGXKbQIzBrGvZclXrYFWKyXEGu@junction.proxy.rlwy.net:48261/railway
    username: root
    password: sJvHdWWGXKbQIzBrGvZclXrYFWKyXEGu
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:mysql://localhost:3306/travel_app?useSSL=false&serverTimezone=UTC
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  secretKey: 90c85b588e8d468d45cf5a70a5517dc6507a0655d7ea0664f6eb70dd4d76394e
  valid-duration: 86400
  refresh-duration: 86400

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: 58X4B4HP
    hashSecret: VRLDWNVWDNPCOEPBZUTWSEDQAGXJCNGZ
    returnUrl: http://localhost:8080/api/v1/payment/vnpay-callback
    version: 2.1.0
    command: pay
    order_type: others




